rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ByteContent\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Classes\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\CmdLineTest1\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\CommonLib\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ConsoleTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Experiment\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Functions\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\NanoTimeTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Parms\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\PrintTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\PrintView\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Program\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ProtoMsg\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ProtoSerial\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ProtoTcpClient\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ProtoTcpServer\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ProtoUdp\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\RisLib\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\SerialComm\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\TableTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\Test\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadNotify\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadQCall\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadSample\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadServices\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadSynch\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\ThreadTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\TimerTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\TimerThreadTest\x64
rmdir /s /q C:\Prime\DevelopLib\Dev_RisLib\TwoThreadTest\x64
